backup:
  keep_local: true # keep the file on workspace folder after upload to storage provider (saveup store)
  prefix: "palworld" # prefix for the backup file, eg: palworld-date-time.zip

workspace:
  path: "" # use absolute path, eg: "/home/ubuntu/saveup_workspace"

save:
  path: "" # use absolute path, eg: "/home/ubuntu/palworld_server/Pal/Saved"

compression:
  format: "zip" # zip

storage:
  provider: r2 # r2

r2:
  endpoint: ""
  bucket: ""
  access_key: ""
  secret_key: ""